# Example configuration.yaml entry
switch:
  - platform: broadlink
    host: 192.168.199.185
    mac: 'B4:43:0D:C7:3A:F9'
    switches:
      reciever:
        command_on: 'switch_packet on'
        command_off: 'switch_packet off'
    switches:
      air:
        friendly_name: "air"
        command_on: 'JgDYAAABKZEUNBU0FQ8VDxUPFQ8VNBU0FTQUNRQ1FBAUNBUPFQ8VNBUPFQ8VDxUPFBAVNBU0FDUUEBQQExEUEBMRFBATERQQFBAUEBMRExETERQ1FBAUNBUQExETERMRExETERMRExETERMRExETEBQRExAUNRQ1FBAUEBQQFQ8UEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBATERQQFBAUEBQ1FBAUNRMRExETERMRExETNhM2EzUUNRQ1FBASEhQ1FAANBQ=='
        command_off: 'JgDYAAABKZEUNBU0FQ8VDxUPFQ8VNBU0FTQUNRQ1FBAUNBUPFQ8VNBUPFQ8VDxUPFBAVNBU0FDUUEBQQExEUEBMRFBATERQQFBAUEBMRExETERQ1FBAUNBUQExETERMRExETERMRExETERMRExETEBQRExAUNRQ1FBAUEBQQFQ8UEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBAUEBQQFBATERQQFBAUEBQ1FBAUNRMRExETERMRExETNhM2EzUUNRQ1FBASEhQ1FAANBQ=='
